#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("jackApp.Resource", IsApplication=true)]

namespace jackApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int MyButton = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int editTextBook = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int editTextFood = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int editTextNO = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int editTextTot = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout1 = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int spinnerMon = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int spinnerYear = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int textView4Mtot = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int textView4Ntot = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int textViewEdt = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int textViewMtot = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int textViewNtot = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int textViewSdt = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int textViewWorkday = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Query = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int SpinnerMon = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int SpinnerYear = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
